Refactor Person to StudySpot, AddressBook to StudyTracker
AY2122S1-CS2103T-T09-1/tp pull request #22
Opened 2021-09-24 16:46 UTC by qreoct

Refactor more instances of `Person` to `StudySpot`, and `AddressBook` to `StudyTracker`. Part of #11. 

Also made changes to:
- Changed default data file to `data/studytracker.json` from `data/addressbook.json`.
- Main source code, including comments + Test files.
- Partial changes to User Guide and Developer Guide terminology.

2021-09-25 11:56 UTC, joenzkimchan requested changes
All tests pass, just some small changes

2021-09-25 11:56 UTC, joenzkimchan commented on src/main/java/seedu/address/commons/core/Messages.java
> +    public static final String MESSAGE_INVALID_PERSON_DISPLAYED_INDEX = "The study spot index provided is invalid";
Should be named MESSAGE_INVALID_STUDYSPOT_DISPLAYED_INDEX

2021-09-25 11:56 UTC, joenzkimchan commented on src/main/java/seedu/address/model/studyspot/Name.java
> + * Represents a Person's name in the study tracker.
Should represent a studyspot's name

2021-09-25 11:56 UTC, joenzkimchan commented on src/main/java/seedu/address/storage/JsonSerializableStudyTracker.java
> +    public static final String MESSAGE_DUPLICATE_PERSON = "StudySpots list contains duplicate study spot(s).";
should be MESSAGE_DUPLICATE_STUDYSPOT

2021-09-25 11:56 UTC, joenzkimchan commented on src/main/java/seedu/address/logic/commands/EditCommand.java
> +    public static final String MESSAGE_EDIT_PERSON_SUCCESS = "Edited study spot: %1$s";
MESSAGE_EDIT_STUDYSPOT_SUCCESS

2021-09-25 11:56 UTC, joenzkimchan commented on src/main/java/seedu/address/logic/commands/AddCommand.java
> +    public static final String MESSAGE_DUPLICATE_PERSON = "This study spot already exists in the study tracker";
MESSAGE_DUPLICATE_STUDYSPOT

2021-09-25 11:56 UTC, joenzkimchan commented on src/main/java/seedu/address/commons/core/Messages.java
> +    public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d study spot(s) listed!";
MESSAGE_STUDYSPOTS_LISTED_OVERVIEW

2021-09-25 16:04 UTC, mslevis reviewed
Good job! just missed out some variables

2021-09-26 06:27 UTC, mslevis approved these changes

2021-09-26 06:36 UTC, joenzkimchan approved these changes
LGTM!

2021-09-26 06:36 UTC, merged