Implement Add Amenities (Wifi)
AY2122S1-CS2103T-T09-1/tp pull request #50
Opened 2021-09-28 19:01 UTC by limdanqi

Implemented the amenities field of study spot, with wifi being the only amenity type now.

Test methods and documentation are not yet included.

Part of #27

2021-09-29 19:35 UTC, limdanqi commented
- Implemented test methods for the Amenity class
- Included documentation for the Amenity class

Resolves #27

2021-09-30 03:17 UTC, qreoct requested changes
Overall looks great!

But will need to work with EditCommand before we can merge. Right now Edit still cannot handle Amenities. A suggestion is to find `PREFIX_TAG` in `EditCommandParser.java` use that to build the edit amenity case (which means more testcases can be written for Edit too... but if that's not the scope of this PR it's fine.)

2021-09-30 03:17 UTC, qreoct commented on src/test/java/seedu/address/model/amenity/AmenityTest.java
> +        assertFalse(Amenity.isValidAmenityType("#wifi"));
Same issue as `JsonAdaptedStudySpotTest.java` where it looks like we are testing for non-alphanumeric characters, when instead we are testing for Amenities not present in our `Amenity.VALID_TYPES` list.

2021-09-30 03:17 UTC, qreoct commented on src/test/java/seedu/address/model/amenity/AmenityTest.java
> +
Would prefer `aircon` instead of `air-con`

2021-09-30 04:19 UTC, limdanqi commented on src/test/java/seedu/address/storage/JsonAdaptedStudySpotTest.java
> +    private static final String INVALID_AMENITY = "#wifi";
Yeah i think that makes better sense!

2021-10-06 04:39 UTC, qreoct approved these changes
Nice!

2021-10-06 04:39 UTC, qreoct commented on src/test/java/seedu/address/storage/JsonSerializableStudyTrackerTest.java
> +    //    }
Test for future review

2021-10-06 04:39 UTC, qreoct commented on src/test/java/seedu/address/logic/parser/StudyTrackerParserTest.java
> +    //    }
Test for future review

2021-10-06 05:24 UTC, merged