Update DG for Architecture section
AY2122S1-CS2103T-T09-1/tp pull request #93
Opened 2021-10-17 17:34 UTC by qreoct

Change diagrams for Architecture section to match StudyTracker.

For Week 10 v1.3 task.

2021-10-17 17:48 UTC, mslevis requested changes
Seems good! Just missed out one line.

2021-10-17 17:48 UTC, mslevis commented on docs/diagrams/ArchitectureSequenceDiagram.puml
>  logic -[LOGIC_COLOR]> model : deletePerson(p)
Perhaps this can be changed to deleteStudySpot as well

2021-10-17 17:57 UTC, limdanqi commented on docs/DeveloperGuide.md
> +The **API** of this component is specified in [`Ui.java`](https://github.com/AY2122S1-CS2103T-T09-1/tp/tree/master/src/main/java/seedu/address/logic)
for this it should be ui/Ui.java instead of logic?

2021-10-17 19:32 UTC, mslevis commented
Other than updating the PlantUML, the diagrams need to be exported before the changes are reflected on the actual documentation. Refer to [here](https://se-education.org/guides/tutorials/plantUml.html)

2021-10-18 12:26 UTC, mslevis approved these changes

2021-10-18 12:26 UTC, merged